version: "3"

services:
    libretranslate:
        container_name: libre_translate
        image: libretranslate/libretranslate
        #ports:
        #    - 5123:5000
        environment:
            LT_LOAD_ONLY: "en,ru"
        volumes:
            - ./_lt_data:/home/libretranslate/.local

    backend:
        container_name: video_search_back
        build: .
        ports:
            - 5100:8080
        depends_on:
            - libretranslate
            - navec
        environment:
            LIBRE_TRANSLATE_URL: http://libretranslate:5000
            NAVEC_API_URL: http://navec:8000
            AVG_DOC_LEN_NGRAMS: 150
        env_file: .env