services:
    libretranslate:
        container_name: libre_translate
        image: libretranslate/libretranslate
        ports:
            - 5123:5000
        environment:
            LT_LOAD_ONLY: "en,ru"
        volumes:
            - ./_lt_data:/home/libretranslate/.local
    navec:
        container_name: navec_api
        build: ./navecApi
        ports:
            - 5124:8000